### ISSUE TITLE
Cards should resize when window size changes

### ISSUE THREAD

**Issue by cannam** [piper-audio/ugly-duckling#26]
The size (specifically, width) of the cards should adjust when the window size changes.

On a mobile device, the action that we care most about is rotating the device . There was a nice suggestion came up in our meeting a while back to make device rotation to landscape mode have the effect of zooming a single card to full-screen. That would be neat, but merely resizing would be a start.

**Comment by LucasThompson** [comment]
The cards do resize dynamically, the issue here is resizing the waves-ui track. I have a feeling this is going to be more awkward than it first seems.

**Comment by LucasThompson** [comment]
I'd wanted to solve this in waves-ui without relying on a resize event from the browser.

I explored changing some of the SVG elements in track and layer to use 100% width, which gets some of the way there. However, ultimately the timeContext has to have its visible width property updated, so that shapes can determine what to draw. So this change could be delayed to user interaction, scrolling panning etc but that is not ideal.

Ultimately I had to use the resize event - thus no changes are needed to waves-ui. The solution here has some issues, and might be refactored at a later date.
